services:
  - type: web
    name: whatbot
    env: node
    buildCommand: npm install
    startCommand: npm run render-start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: IS_RENDER
        value: true
      - key: NODE_ENV
        value: production
    disk:
      name: tmp-data
      mountPath: /tmp
      sizeGB: 1
