services:
  - type: web
    name: whatbot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: tmp-data
      mountPath: /tmp
      sizeGB: 1
