services:
  - type: worker
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: IS_RENDER
        value: true
      - key: NODE_ENV
        value: production
    disk:
      name: tmp-data
      mountPath: /tmp
      sizeGB: 1
